### PR TITLE
Add support for IBM Cloud Billing Converter

### PR DESCRIPTION
**Pull request by chrisw-ibm**
Support for using the converter to map IBM Cloud Billing Report CSV to the FOCUS specification.

- An anonymized billing sample has been added for testing purposes
- Unit test added for the billing csv

- The data_loader was modified to support IBM Cloud's non-standard csv format which contains a header at the top of the CSV. This metadata is duplicated and concatenated to the billing line items.
- progress and conversion rules export reports have been added

### CODE REVIEW

**Comment by varunmittal91** [comment]
@chrisw-ibm thank you this is great. I approved run, it's builing as soon as done I can merge it back.

**Comment by chrisw-ibm** [comment]
@varunmittal91 I pushed the fix for the linting error on the import order. Can you approve the run again :)

**Comment by varunmittal91** [comment]
@chrisw-ibm sorry for the back and forth
here's the patch on the formatting error
[formatting.patch](https://github.com/user-attachments/files/16755299/formatting.patch)

**Comment by chrisw-ibm** [comment]
Thanks for the patch. All checks pass now!

**Comment by varunmittal91** [comment]
> Thanks for the patch. All checks pass now!

Thank you so much @chrisw-ibm, this is awesome.

**Comment by varunmittal91** [comment]
> > Thanks for the patch. All checks pass now!
> 
> Thank you so much @chrisw-ibm, this is awesome.

Hey also realized we need to add IBM to supported list of cloud vendors on the README and add the piechart. I would love to connect and discuss more on this.

**Pull request merged**
