### PR TITLE
Fixes Issue #101 and Issue #102

### PR DESCRIPTION
**Pull request by davidschneider2W**

### CODE REVIEW

**Comment by varunmittal91** [comment]
Hi @davidschneider2W , thanks for the PR, I was wondering that since this uses AWS CUR 2.0, what will happen to data that was exported prior to CUR 2.0?

**Comment by davidschneider2W** [comment]
this is a good question, i will set up a legacy export to test on before merging

**Comment by davidschneider2W** [comment]
@varunmittal91 are you referring to "Legacy CUR"? If so it seems like Sub Account Name is not actually present (as well as Billing Account Name) in the old style dataset. That seems to be the `aws-cur` set of conversion configs. I can add an extra rule file for Sub Account ID there.

**Comment by varunmittal91** [comment]
Thank you @davidschneider2W that makes sense.

There are couple of thinkgs we can do here,
either we can create a whole new provider for AWS CUR 2.0 and copy over the set with additional rules such as SubAccountName or add it to existing set with a check that ensures that required source columns are present.

**Comment by varunmittal91** [comment]
Let me know what do you think?

**Comment by varunmittal91** [comment]
Hi @davidschneider2W , I also created a PR to allow more dynamic custom plugins for more complicated use cases that are hard to define through a YAML.

https://github.com/finopsfoundation/focus_converters/pull/343

Here's a sample plugin:

```python
@focus_conversion(plan_name="test-plan-universal")
class CustomConversionPlugin(BaseFOCUSConverterPlugin):
    @classmethod
    def get_arguments_model(cls) -> Optional[Type[BaseModel]]:
        class CustomModel(BaseModel):
            arg1: str

        return CustomModel

    @classmethod
    def conversion_plan_hook(cls, plan, column_validator) -> pl.Expr:
        return pl.col(plan.column).str.replace("_", "Provider")
```

I can explain in more detail it it makes sense.

**Pull request closed without merging**
