### PR TITLE
addition of focus column PricingCategory

### PR DESCRIPTION
**Pull request by csyvenky-finops**
#283

### CODE REVIEW

**Comment by varunmittal91** [comment]
Hi @csyvenky-finops default_value would have to be '''Other'''

Basically two single quotes and the value in between and again two single quotes.

This is to factor how YAML treats strings and how sql treats constants and column names.

**Comment by csyvenky-finops** [comment]
I've just attempted three commits and all fail the PR checks.

1. double + single i.e., "'value'"
2. two singles i.e., ''value''
3. three singles i.e., '''value'''

**Comment by varunmittal91** [comment]
@csyvenky-finops, I am sorry I was trying to add a review commit but it ended up writing one commit on top.

We needed it to be enclosed in double_quotes:
default_value: "'Other'"

If you think this works let me know and we can merge this.

**Comment by csyvenky-finops** [comment]
Hello, that's fine by me. What I don't understand is that via commit id: 83414246b7777be8f29c8f51c20e6dcf79dc8350, you'll see that I tried that already and it failed the checks. Hopefully [291](https://github.com/finopsfoundation/focus_converters/pull/291) and [295 ](https://github.com/finopsfoundation/focus_converters/pull/295) are both ready for merge.

**Comment by varunmittal91** [comment]
On one I was missing the definition of PricingCategory all together, so as soon as I added it worked.
On the other it was the yaml issue, what we needed to do was "'Other'".

Anyways I will go and merge this in.

**Pull request merged**
